# Generated by Django 4.2.11 on 2024-05-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturerId', models.AutoField(primary_key=True, serialize=False)),
                ('lFirstName', models.CharField(max_length=100, null=True)),
                ('lLastName', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteid', models.AutoField(primary_key=True, serialize=False)),
                ('noteName', models.CharField(max_length=100)),
                ('noteDescription', models.TextField()),
                ('noteURL', models.URLField()),
                ('extension', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('cmsId', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='savedNote',
            fields=[
                ('noteid', models.AutoField(primary_key=True, serialize=False)),
                ('noteName', models.CharField(max_length=100)),
                ('noteDescription', models.TextField()),
                ('noteURL', models.URLField()),
                ('extension', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('cmsId', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('tags', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('UserProfileId', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pfpURL', models.URLField()),
                ('learningInstitution', models.CharField(max_length=100)),
                ('courseMajor', models.CharField(max_length=100)),
                ('interests', models.TextField()),
                ('savedNotes', models.TextField()),
                ('likedNotes', models.TextField()),
                ('following', models.TextField()),
                ('isCreator', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
