# Generated by Django 4.2.11 on 2024-05-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuserprofile',
            name='profileId',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
