# Generated by Django 4.2.11 on 2024-05-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coreuserprofile_profileid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningInstitution',
            fields=[
                ('institutionId', models.AutoField(primary_key=True, serialize=False)),
                ('institutionName', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='coreuserprofile',
            name='learningInstitution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.learninginstitution'),
        ),
    ]
