# Generated by Django 4.2.11 on 2024-05-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_learninginstitution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interestId', models.AutoField(primary_key=True, serialize=False)),
                ('interestName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='coreuserprofile',
            name='interests',
            field=models.ManyToManyField(to='core.interest'),
        ),
    ]
