# Generated by Django 4.2.11 on 2024-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interest_coreuserprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuserprofile',
            name='courseMajor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coreuserprofile',
            name='fullName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreuserprofile',
            name='profileId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coreuserprofile',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
