# Generated by Django 4.2.11 on 2024-05-27 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_coreuserprofile_coursemajor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreuserprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='coreuserprofile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
