# Generated by Django 4.2.11 on 2024-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_coreuserprofile_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreuserprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='coreuserprofile',
            name='interests',
            field=models.ManyToManyField(to='core.interest'),
        ),
    ]
