# Generated by Django 4.2.11 on 2024-05-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_coreuserprofile_interests_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coreuserprofile',
            table='userprofile',
        ),
        migrations.AlterModelTable(
            name='interest',
            table='interests',
        ),
        migrations.AlterModelTable(
            name='learninginstitution',
            table='learninginstitution',
        ),
    ]
