# Generated by Django 4.2.11 on 2024-05-28 20:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_userprofile_profileid_userprofile_clerkid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customUserInterest',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
