# Generated by Django 4.2.11 on 2024-05-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_id_userprofile_profileid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
    ]
