# Generated by Django 4.2.11 on 2024-05-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_major_user_usereducationdetails_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducationdetails',
            name='learning_institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='core.learninginstitution'),
        ),
    ]
