# Generated by Django 4.2.11 on 2024-05-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_usereducationdetails_learning_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducationdetails',
            name='learning_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learninginstitution'),
        ),
        migrations.AlterField(
            model_name='usereducationdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.user'),
        ),
    ]
