# Generated by Django 5.0.6 on 2024-05-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_major_major_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='major_abbreviation',
        ),
    ]
