# Generated by Django 4.2.11 on 2024-06-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_interestid_interest_interest_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereducationdetails',
            old_name='user',
            new_name='oto_user',
        ),
    ]
