# Generated by Django 4.2.11 on 2024-06-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_notesupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesupload',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
