# Generated by Django 5.0.6 on 2024-06-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_waitlist_created_at_remove_waitlist_fx_major_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waitlist',
        ),
    ]
