# Generated by Django 5.0.6 on 2024-06-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'resource_types',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_url', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField()),
                ('cms_id', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resourcetype')),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interest')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
            ],
            options={
                'db_table': 'resource_tags',
                'unique_together': {('resource', 'interest')},
            },
        ),
    ]
