# Generated by Django 4.2.9 on 2024-06-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducationdetails',
            name='fx_full_name',
            field=models.ForeignKey(default=75, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
