# Generated by Django 4.2.9 on 2024-06-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducationdetails',
            name='fx_full_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user', to_field='full_name'),
        ),
    ]
