# Generated by Django 4.2.9 on 2024-06-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_notesupload_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesUpload',
        ),
    ]
