# Generated by Django 4.2.9 on 2024-06-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_delete_notesupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
