# Generated by Django 4.2.9 on 2024-06-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_notesupload_note_folder'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='folder',
            table='folders',
        ),
    ]
