# Generated by Django 4.2.9 on 2024-06-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_folder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='resources',
            field=models.ManyToManyField(to='core.resource'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
