# Generated by Django 4.2.9 on 2024-06-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_folder_resources_alter_folder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
