# Generated by Django 4.2.9 on 2024-06-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_folder_name_alter_folder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'name')},
        ),
        migrations.DeleteModel(
            name='FolderName',
        ),
    ]
